-- This file should undo anything in `up.sql`
-- down.sql
DROP TABLE USER_ROLES;
DROP TABLE TICKET_ASSIGNMENTS;
DROP TABLE COMMENTS;
DROP TABLE TICKETS;
DROP TABLE STATUSES;
DROP TABLE SYSTEMS;
DROP TABLE ROLES;
DROP TABLE USERS;
DROP TABLE AUDITS;